# Generated by Django 2.0.2 on 2018-02-28 03:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hadTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=25)),
                ('lastName', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=17)),
            ],
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=35)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.person')),
            ],
        ),
        migrations.CreateModel(
            name='sells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='store.items')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.seller')),
            ],
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('premium', models.BooleanField()),
                ('created', models.DateField(blank=True, default=datetime.datetime.now)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.person')),
            ],
        ),
        migrations.AddField(
            model_name='hadtag',
            name='itemName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.items'),
        ),
        migrations.AddField(
            model_name='hadtag',
            name='itemTag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.tag'),
        ),
    ]
