# Generated by Django 2.0.2 on 2018-03-02 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='img',
            field=models.ImageField(default='static/img/imgPlaceHolder.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
