# Generated by Django 2.0.2 on 2018-03-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20180302_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='img',
            field=models.ImageField(default='static/img/imgPlaceHolder.png', upload_to='static_cdn/itemImg/'),
        ),
    ]
