# Generated by Django 2.0.2 on 2018-03-02 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20180302_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name_plural': 'items'},
        ),
        migrations.AlterModelOptions(
            name='sells',
            options={'verbose_name_plural': 'sells'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='seller',
            name='companyName',
        ),
    ]
